# Generated by Django 6.0.4 on 2026-04-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=70)),
                ('no_calle', models.IntegerField()),
                ('pais', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='dom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.domicilio'),
        ),
    ]
